// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfxjixfypskoorapbulw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmeGppeGZ5cHNrb29yYXBidWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODA0OTAsImV4cCI6MjA2NjU1NjQ5MH0.xxdL4dIATToM5k_yYiB1m4hfAPDb_vFZsYZXaNz-Woc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);